### ISSUE TITLE
Remove use of boost::optional

### ISSUE THREAD

**Issue by lolisa** [lolisa/first_order_logic_prover#33]
Fucking waste three hour debugging bug from boost::optional implicit conversion.

**Comment by FrankHB** [comment]
Does `std::experimental::optional` has same issue? Please give the detailed description.
BTW, an implementation of [WG21/N4081](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4081.html) aiming to be simpler and more reliable than libstdc++/libc++'s `std::experimental::optional` is [under construction](https://github.com/FrankHB/YSLib/blob/master/YBase/include/ystdex/optional.h) and would be committed in next revision (implementation completed but not tested yet).

**Comment by lolisa** [comment]
Don't know about std::experimental::optional, the only problem is that boost::optional allow implicit conversion of bool, so my code relying on boost::optional<bool> is extremely fraudulent to refactor change, such as refactoring some bool to some enum type.

**Comment by lolisa** [comment]
std::experimental::optional dont have this problem because it's explicit constructor.
